version: '3'
services:
  golang:
    # will build ./docker/web/Dockerfile
    build: ./golang/
    ports:
     - "8001:8001"
  nodejs:
    build: ./nodejs/
    ports:
     - "8003:8003"
  php:
    build: ./php/
    ports:
     - "8004:8004"
  python:
    build: ./python/
    ports:
     - "8005:8005"
